porting this plugin base on sf version
EC-CUBE/Recommend-plugin pull request #25
Opened 2018-05-18 11:29 UTC by hoand-vn

## 概要(Overview・Refs Issue)
+ PullRequestの目的、関連するIssue番号など
  - porting for SF

## 方針(Policy)
+ このPullRequestを作るにあたって考慮したものや除外した内容
  - none

2018-07-10 07:41 UTC, ryo-endo requested changes

2018-07-10 07:41 UTC, ryo-endo commented on Repository/RecommendProductRepository.php
> +        $qb->where('rp.visible = ' . Constant::ENABLED);
visibleはboolean型です。
いまのままだと、管理画面>おすすめ商品管理 のページを表示したときにエラーが発生します。
```
SQLSTATE[42883]: Undefined function: 7 ERROR: 演算子が存在しません: boolean = integer
LINE 1: ...criminator_type IN ('product') WHERE (p0_.visible = 1) AND p...
```

2018-07-10 07:41 UTC, ryo-endo commented on Repository/RecommendProductRepository.php
> +            ->where('rp.visible = '.Constant::ENABLED)
`visible` is boolean

2018-07-10 07:42 UTC, ryo-endo requested changes
商品検索したときに失敗します。

![image](https://user-images.githubusercontent.com/16891862/42496188-3a38244a-8460-11e8-90b7-0bde10becdae.png)

2018-07-10 07:48 UTC, ryo-endo requested changes
ブロックを追加して、TOPページを表示するとエラーが表示されます。

```
Twig_Error_Runtime
Neither the property "config" nor one of the methods "config()", "getconfig()"/"isconfig()"/"hasconfig()" or "__call()" exist and have public access in class "Symfony\Bridge\Twig\AppVariable".
```
```
in Eccube/Resource/template/default/block.twig (line 14)
```

2018-07-10 07:49 UTC, ryo-endo requested changes
'@admin/styleguide_frame.twig'
↓
'@admin/default_frame.twig'

2018-07-11 08:10 UTC, lqdung-lockon commented
@ryo-endo -san, @hoand-vn -san,

Since it's too old and still does not apply changes from the source code. Please close it.

2018-07-11 08:11 UTC, hoand-vn commented
fixing time

2018-07-12 03:43 UTC, hoand-vn commented
finish fixing

2018-10-02 05:43 UTC, merged